#!/usr/local/bin/ruby
require File.dirname(__FILE__) + "/timeBookCalendar"
require "cgi-lib"
input = CGI.new

print "Content-type: text/html;charset=UTF-8\n\n"
print "<html>"
print "<head>"
print "<title>入力画面</title>"
print "<meta http-equiv=\"Content-type\" content=\"text/html;charset=utf-8\"/>"
print "</head>"
print "<body>"
print "<form action=\"./timeBook.cgi\" method=\"POST\">"
print "<table border=\"3\" cellspacing=\"0\" cellpadding=\"2\">"
print "<caption>#{input['year']} / #{input['month']}</caption>"
print "<tr>"
print "<th>day</th>"
print "<th>date</th>"
print "<th>start</th>"
print "<th>end</th>"
print "<th>memo</th>"
print "</tr>"
print "<tr>"
print "<td>#{input['day']}</td>"
print "<td>Wed</td>"
print "<td><input type=\"text\" id=\"start\" name=\"start\" value=\"\"/></td>"
print "<td><input type=\"text\" id=\"end\" name=\"end\" value=\"\"/></td>"
print "<td><input type=\"text\" id=\"memo\" name=\"memo\" value=\"\"/></td>"
print "</tr>"
print "</table>"
print "<input type=\"submit\" name=\"登録\"/>"
print "</form>"
print "</body>"
print "</html>"

